application: tapatch-16 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

-  url: /js
   static_dir: js
   
-  url: /css
   static_dir: css

-  url: /views
   static_dir: views 

-  url: /images
   static_dir: images

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

-  url: /.*
   script: tapatch.application
   
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest   
